/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIPerpustakaan;

import java.util.ArrayList;
import java.util.List;
import perpustakaankampus.Buku;

/**
 *
 * @author User
 */
public class MenuListBuku extends javax.swing.JFrame {

    /**
     * Creates new form MenuListBuku
     */
    public MenuListBuku() {
        initComponents();
    }
    
    List<Buku> listBuku = new ArrayList();
        listBuku.add(new Buku("B001", "Good to Great: Why Some Compan", "Jim Collins", "Dalam buku ini, Collins menganalisis perusahaan-perusahaan yang berhasil bertransformasi dari yang baik menjadi luar biasa. Dengan menggunakan penelitian yang mendalam, dia mengidentifikasi pola-pola ", "Bisnis", "2001", 5, 10));
        listBuku.add(new Buku("B002", "Lean In: Women, Work", "Blake Masters", "Sandberg, Chief Operating Officer Facebook, mengajak wanita untuk mengambil peran aktif dalam dunia kerja dan memperjuangkan kesetaraan gender. Dia membahas tantangan yang dihadapi oleha wanita di tempat", "2013", "2001", 5, 4));
        listBuku.add(new Buku("B003", "The 7 Habits", "Stephen R. Covey", "Covey mengidentifikasi tujuh kebiasaan yang dimiliki oleh orang-orang yang sangat efektif dalam hidup dan bisnis. Dari kebiasaan mengutamakan hal-hal penting hingga berusaha memahami terlebih dahulu saja.", "Bisnis", "1989", 5, 8));
        listBuku.add(new Buku("B004", "Zero to One", "Blake Masters", "Zero to One (2014) mengungkap cara membangun sebuah perusahaan startup sukses yang mampu menjawab tantangan masa depan yang penuh dengan ketidakpastian. Di dalam buku ini Anda juga akan mempelajari prinsip-prinsip yang harus dimiliki oleh sebuah peru", "Bisnis", "2014", 5, 16));
        listBuku.add(new Buku("B005", "The Monk and The Riddle", "Randy Komisar", "\\\"The Monk and the Riddle\\\" adalah sebuah buku yang mengisahkan perjalanan hidup seorang pengusaha sukses yang mencari arti sejati dalam hidupnya. Cerita ini mengungkapkan konflik antara keinginan untuk menghasilkan keuntungan finansial dan kepuasan pr", "Bisnis", "2000", 5, 3));
        listBuku.add(new Buku("B006", "To Kill a Mockingbird", "Harper Lee", "\\\"To Kill a Mockingbird\\\" adalah sebuah novel klasik yang ditulis oleh Harper Lee.\\", "Bisnis", "1960", 5, 7));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        AbstrakBukuRec1 = new javax.swing.JLabel();
        ViewBukuRec1 = new javax.swing.JButton();
        BukuRec1 = new javax.swing.JLabel();
        TahunTerbitBukuRec1 = new javax.swing.JLabel();
        Header1 = new javax.swing.JLabel();
        ViewBukuRec10 = new javax.swing.JButton();
        BukuRec6 = new javax.swing.JLabel();
        TahunTerbitBukuRec3 = new javax.swing.JLabel();
        AbstrakBukuRec3 = new javax.swing.JLabel();
        BukuRec7 = new javax.swing.JLabel();
        TahunTerbitBukuRec4 = new javax.swing.JLabel();
        AbstrakBukuRec4 = new javax.swing.JLabel();
        ViewBukuRec6 = new javax.swing.JButton();
        ViewBukuRec11 = new javax.swing.JButton();
        BukuRec8 = new javax.swing.JLabel();
        TahunTerbitBukuRec5 = new javax.swing.JLabel();
        AbstrakBukuRec5 = new javax.swing.JLabel();
        ViewBukuRec12 = new javax.swing.JButton();
        BukuRec9 = new javax.swing.JLabel();
        TahunTerbitBukuRec9 = new javax.swing.JLabel();
        AbstrakBukuRec9 = new javax.swing.JLabel();
        ViewBukuRec13 = new javax.swing.JButton();
        BukuRec10 = new javax.swing.JLabel();
        TahunTerbitBukuRec10 = new javax.swing.JLabel();
        AbstrakBukuRec10 = new javax.swing.JLabel();
        ViewBukuRec14 = new javax.swing.JButton();
        BukuRec11 = new javax.swing.JLabel();
        TahunTerbitBukuRec11 = new javax.swing.JLabel();
        AbstrakBukuRec11 = new javax.swing.JLabel();
        ViewBukuRec15 = new javax.swing.JButton();
        BukuRec12 = new javax.swing.JLabel();
        TahunTerbitBukuRec12 = new javax.swing.JLabel();
        AbstrakBukuRec12 = new javax.swing.JLabel();

        Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Header.setText("Perpustakaan Kampus");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbstrakBukuRec1.setText("Abstrak Buku 1");
        AbstrakBukuRec1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec1.setText("Detail.");
        ViewBukuRec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec1ActionPerformed(evt);
            }
        });

        BukuRec1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec1.setText("Buku 1");
        BukuRec1.setName(""); // NOI18N

        TahunTerbitBukuRec1.setText("Tahun Rilis Buku 1");

        Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Header1.setText("Perpustakaan Kampus");

        ViewBukuRec10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec10.setText("Detail.");
        ViewBukuRec10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec10ActionPerformed(evt);
            }
        });

        BukuRec6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec6.setText("Buku 3");
        BukuRec6.setName(""); // NOI18N

        TahunTerbitBukuRec3.setText("Tahun Rilis Buku 3");

        AbstrakBukuRec3.setText("Abstrak Buku 3");
        AbstrakBukuRec3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BukuRec7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec7.setText("Buku 2");
        BukuRec7.setName(""); // NOI18N

        TahunTerbitBukuRec4.setText("Tahun Rilis Buku 2");

        AbstrakBukuRec4.setText("Abstrak Buku 2");
        AbstrakBukuRec4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec6.setText("Detail.");
        ViewBukuRec6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec6ActionPerformed(evt);
            }
        });

        ViewBukuRec11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec11.setText("Detail.");
        ViewBukuRec11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec11ActionPerformed(evt);
            }
        });

        BukuRec8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec8.setText("Buku 4");
        BukuRec8.setName(""); // NOI18N

        TahunTerbitBukuRec5.setText("Tahun Rilis Buku 4");

        AbstrakBukuRec5.setText("Abstrak Buku 4");
        AbstrakBukuRec5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec12.setText("Detail.");
        ViewBukuRec12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec12ActionPerformed(evt);
            }
        });

        BukuRec9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec9.setText("Buku 5");
        BukuRec9.setName(""); // NOI18N

        TahunTerbitBukuRec9.setText("Tahun Rilis Buku 5");

        AbstrakBukuRec9.setText("Abstrak Buku 5");
        AbstrakBukuRec9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec13.setText("Detail.");
        ViewBukuRec13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec13ActionPerformed(evt);
            }
        });

        BukuRec10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec10.setText("Buku 6");
        BukuRec10.setName(""); // NOI18N

        TahunTerbitBukuRec10.setText("Tahun Rilis Buku 6");

        AbstrakBukuRec10.setText("Abstrak Buku 6");
        AbstrakBukuRec10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec14.setText("Detail.");
        ViewBukuRec14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec14ActionPerformed(evt);
            }
        });

        BukuRec11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec11.setText("Buku 7");
        BukuRec11.setName(""); // NOI18N

        TahunTerbitBukuRec11.setText("Tahun Rilis Buku 7");

        AbstrakBukuRec11.setText("Abstrak Buku 7");
        AbstrakBukuRec11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewBukuRec15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ViewBukuRec15.setText("Detail.");
        ViewBukuRec15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBukuRec15ActionPerformed(evt);
            }
        });

        BukuRec12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BukuRec12.setText("Buku 8");
        BukuRec12.setName(""); // NOI18N

        TahunTerbitBukuRec12.setText("Tahun Rilis Buku 8");

        AbstrakBukuRec12.setText("Abstrak Buku 8");
        AbstrakBukuRec12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewBukuRec6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TahunTerbitBukuRec10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AbstrakBukuRec10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BukuRec10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ViewBukuRec13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TahunTerbitBukuRec4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AbstrakBukuRec4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BukuRec7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTerbitBukuRec12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AbstrakBukuRec12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BukuRec12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewBukuRec15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec1)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec7)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec6)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec8)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec9)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec10)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec11)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BukuRec12)
                        .addGap(3, 3, 3)
                        .addComponent(TahunTerbitBukuRec12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbstrakBukuRec12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewBukuRec15)))
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBukuRec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec1ActionPerformed

    private void ViewBukuRec10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec10ActionPerformed

    private void ViewBukuRec6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec6ActionPerformed

    private void ViewBukuRec11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec11ActionPerformed

    private void ViewBukuRec12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec12ActionPerformed

    private void ViewBukuRec13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec13ActionPerformed

    private void ViewBukuRec14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec14ActionPerformed

    private void ViewBukuRec15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBukuRec15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBukuRec15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuListBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbstrakBukuRec1;
    private javax.swing.JLabel AbstrakBukuRec10;
    private javax.swing.JLabel AbstrakBukuRec11;
    private javax.swing.JLabel AbstrakBukuRec12;
    private javax.swing.JLabel AbstrakBukuRec3;
    private javax.swing.JLabel AbstrakBukuRec4;
    private javax.swing.JLabel AbstrakBukuRec5;
    private javax.swing.JLabel AbstrakBukuRec9;
    private javax.swing.JLabel BukuRec1;
    private javax.swing.JLabel BukuRec10;
    private javax.swing.JLabel BukuRec11;
    private javax.swing.JLabel BukuRec12;
    private javax.swing.JLabel BukuRec6;
    private javax.swing.JLabel BukuRec7;
    private javax.swing.JLabel BukuRec8;
    private javax.swing.JLabel BukuRec9;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header1;
    private javax.swing.JLabel TahunTerbitBukuRec1;
    private javax.swing.JLabel TahunTerbitBukuRec10;
    private javax.swing.JLabel TahunTerbitBukuRec11;
    private javax.swing.JLabel TahunTerbitBukuRec12;
    private javax.swing.JLabel TahunTerbitBukuRec3;
    private javax.swing.JLabel TahunTerbitBukuRec4;
    private javax.swing.JLabel TahunTerbitBukuRec5;
    private javax.swing.JLabel TahunTerbitBukuRec9;
    private javax.swing.JButton ViewBukuRec1;
    private javax.swing.JButton ViewBukuRec10;
    private javax.swing.JButton ViewBukuRec11;
    private javax.swing.JButton ViewBukuRec12;
    private javax.swing.JButton ViewBukuRec13;
    private javax.swing.JButton ViewBukuRec14;
    private javax.swing.JButton ViewBukuRec15;
    private javax.swing.JButton ViewBukuRec6;
    // End of variables declaration//GEN-END:variables
}
